name: Bug report Bug
description: Report errors or unexpected behavior.
labels: [bug]
title: "[Bug] Short description."
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting issues of WSA-Script!

        To make it easier for us to help you please enter detailed information below.
        
        WSA-Script
  - type: textarea
    attributes:
      label: Steps to reproduce
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      placeholder: Tell us what should happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
      placeholder: Tell us what happens instead
    validations:
      required: true
  - type: input
    attributes:
      label: WSA-Script commit full SHA
      description:  Don't use 'latest'. Copy and paste full commit SHA, otherwise your issue will be closed. commit SHA，issue
    validations:
      required: true
  - type: input
    attributes:
      label: Windows version
      description: Win key + R -> "winver"
      placeholder: 10.0.22000.978
    validations:
      required: true
  - type: input
    attributes:
      label: Build Issue number
      description: Specify the issue number used for the build
      placeholder: #13
    validations:
      required: true
  - type: checkboxes
    id: latest
    attributes:
      label: Version requirement
      options:
        - label: I am using latest commit of WSA-Script commit 
          required: true
