name: Shell checker

on:
  push:
    branches:
      - main
    paths:
      - '**.sh'
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout
      uses: actions/checkout@v3

    - name: Run ShellCheck
      id: check
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC2086 -e SC2034 -e SC1089
      with:
       scandir: './scripts'
